name: cve-scan
on:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build images
        shell: bash
        run: |
          docker build -t cli
      - name: Scan image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: cli
          fail-build: false
          severity-cutoff: critical
          add-cpes-if-none: true
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Inspect scan result
        id: report
        uses: anchore/scan-action@v3
        with:
          image: cli
          output-format: table
          fail-build: true
          severity-cutoff: critical
          add-cpes-if-none: true
