name: verify-action
on:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "master"

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: Demonsthere/cli-action:v1.0.0
        with:
          command: "version"
